(action:send-wait 1000)

(action:send-mouse-absolute-move 185 110)
(action:send-wait 100)
(action:send-mouse-button-press 1)
(action:send-wait 100)
(action:send-mouse-relative-move 500 0)
(action:send-wait 100)
(action:send-mouse-button-release 1)

(action:send-wait 100)
(action:send-key-click 14)
(action:send-wait 100)
(action:send-text-type "What is Linux?")
(action:send-wait 100)
(action:send-key-press 28)
(action:send-wait 100)
(action:send-key-release 28)
(action:send-wait 1000)

(action:send-mouse-relative-move 0 300)
(action:send-wait 100)
(action:send-mouse-button-click 1)
